export const USERS = [
  {
    id: 01,
    firstName: "Irving",
    lastName: "Angulo",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/irvang",
    linkedinUrl: 'http://www.linkedin.com/irvang',
    phone: "617-123-4567",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Angulo.jpeg"
  },
  {
    id: 02,
    firstName: "Ninon",
    lastName: "Becquart",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Becquart.jpeg"
  },
  {
    id: 03,
    firstName: "Melissa",
    lastName: "Cruz",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Cruz.jpg"
  },
  {
    id: 04,
    firstName: "Clydies",
    lastName: "Freeman",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Freeman.jpeg"
  },
  {
    id: 05,
    firstName: "Amber",
    lastName: "Hampton",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Hampton.jpg"
  },
  {
    id: 06,
    firstName: "Angel",
    lastName: "Juarbe",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Juarbe.jpeg"
  },
  {
    id: 07,
    firstName: "Sydney",
    lastName: "Kinchen",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Kinchen.jpeg"
  },
  {
    id: 08,
    firstName: "Jasen",
    lastName: "Lambright",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Lambright.jpeg"
  },
  {
    id: 09,
    firstName: "Ayana",
    lastName: "Murakami-Freeberg",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Murakami-Freeberg.jpeg"
  },
  {
    id: 10,
    firstName: "Jennifer",
    lastName: "Recinos",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Recinos.jpeg"
  },
  {
    id: 11,
    firstName: "Isaiah",
    lastName: "Vertus",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Vertus.jpeg"
  },
  {
    id: 12,
    firstName: "Michelle",
    lastName: "von Vogler",
    year: 2018,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-von-Vogler.jpeg"
  },
  {
    id: 13,
    firstName: "Anthony",
    lastName: "Beckford",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Beckford.jpg"
  },
  {
    id: 14,
    firstName: "Tahj",
    lastName: "Easington",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Easington.jpg"
  },
  {
    id: 15,
    firstName: "Darlene",
    lastName: "Julien",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Julien.jpg"
  },
  {
    id: 16,
    firstName: "Nadia",
    lastName: "Lazo",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Lazo.jpg"
  },
  {
    id: 17,
    firstName: "Kewanee",
    lastName: "McGhee",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-McGhee.jpg"
  },
  {
    id: 18,
    firstName: "Arnold",
    lastName: "Pires",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Pires.jpg"
  },
  {
    id: 19,
    firstName: "Carina",
    lastName: "Saint Germain",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Saint-Germain.jpg"
  },
  {
    id: 20,
    firstName: "Kiki",
    lastName: "Taboh",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Taboh.jpg"
  },
  {
    id: 21,
    firstName: "Helen",
    lastName: "Tran",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Tran.jpg"
  },
  {
    id: 22,
    firstName: "Tomiqua",
    lastName: "Williams",
    year: 2019,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Williams.jpg"
  },
  {
    id: 23,
    firstName: "Adolph",
    lastName: "DuBose",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-DuBose.jpg"
  },
  {
    id: 24,
    firstName: "Andy",
    lastName: "Louis Jean",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Jean.jpg"
  },
  {
    id: 25,
    firstName: "Zin",
    lastName: "Ma",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Cruz.jpg"
  },
  {
    id: 26,
    firstName: "Karlisha",
    lastName: "Mcquitter",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Mcquitter.jpg"
  },
  {
    id: 27,
    firstName: "Jackie",
    lastName: "Mercado",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Mercado.jpg"
  },
  {
    id: 28,
    firstName: "Lorreno",
    lastName: "Pierre",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Pierre.png"
  },
  {
    id: 29,
    firstName: "Melissa",
    lastName: "Sawyer",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Sawyer.jpg"
  },
  {
    id: 30,
    firstName: "Khalid",
    lastName: "Sharmarke",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Sharmarke.jpg"
  },
  {
    id: 31,
    firstName: "Lois",
    lastName: "Simpson",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Simpson.jpg"
  },
  {
    id: 32,
    firstName: "Tevin",
    lastName: "Stowers",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Stowers.jpg"
  },
  {
    id: 33,
    firstName: "Jamie",
    lastName: "Thompson",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Thompson.jpg"
  },
  {
    id: 34,
    firstName: "Brittany",
    lastName: "Tinsley",
    year: 2020,
    email: "fake@email.com",
    githubUrl: "http://www.github.com/fakegithubURL",
    linkedinUrl: 'http://www.linkedin.com/fakelinkedInURL',
    phone: "###-###-####",
    bio:  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur at nesciunt assumenda maxime voluptatibus reiciendis. Beatae itaque obcaecati, optio illum voluptatum ex esse explicabo animi, magni, repellendus totam nemo quibusdam?",
    photo: "http://localhost:5000/images/headshot-Tinsley.jpg"
  },
]

